sudo: required
services:
    - docker

language: generic    

before_install:
    - docker build -t dennisent/docker-react -f Dockerfile.dev .

script: 
    - docker run -e  CI=true dennisent/docker-react npm run test